name: Bump formulae on schedule or request

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/autobump.yml
  workflow_dispatch:
    inputs:
      formulae:
        description: Custom list of formulae to livecheck and bump if outdated
        required: false
  schedule:
    # Every 3 hours with an offset of 15 minutes
    - cron: "15 */3 * * *"

permissions:
  contents: read

jobs:
  autobump:
    if: github.repository_owner == 'Homebrew'
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
    env:
      GNUPGHOME: /tmp/gnupghome
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: true
          cask: false
          test-bot: false

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master
        with:
          username: ${{ (github.event_name == 'workflow_dispatch' && github.actor) || 'BrewTestBot' }}

      - name: Set up commit signing
        uses: Homebrew/actions/setup-commit-signing@master
        with:
          signing_key: ${{ secrets.BREWTESTBOT_GPG_SIGNING_SUBKEY }}

      - name: Bump formulae
        env:
          HOMEBREW_TEST_BOT_AUTOBUMP: 1
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_CORE_REPO_WORKFLOW_TOKEN }}
          HOMEBREW_GPG_PASSPHRASE: ${{ secrets.BREWTESTBOT_GPG_SIGNING_SUBKEY_PASSPHRASE }}
          FORMULAE: ${{ inputs.formulae }}
        run: |
          if [[ -n "${FORMULAE}" ]]; then
            xargs brew bump --no-fork --open-pr --formulae <<<"${FORMULAE}"
          else
            brew bump --no-fork --open-pr --auto --formulae --tap=Homebrew/core
          fi
